### ISSUE TITLE
AttributeError: 'ParserState' object has no attribute 'proj_order'

### ISSUE THREAD

**Issue by amulyahwr** [alirezamshi/G2GTr#1]
Hello,

Thank you for the great work. I was going through your implementation and after performing the following step: 
To include SWAP operation, you should add transition.py file to transitoin.py file of arc-swift repository.

I run: python gen_oracle_seq.py ../data/train.conll train.seq --transsys ASd --mappings ./utils/mappings-ptb.txt
However, 
I receive the error: AttributeError: 'ParserState' object has no attribute 'proj_order'
I think ParserState class in arc-swift -> src -> parserstate.py requires proj_order to be set. Please let me know how to proceed in this case. Thank you in advance.

**Comment by alirezamshi** [comment]
Hello, 

Thanks for your comment. I've added "proj_order" to parserstate.py file. So, you can just copy-paste our transition.py and parserstate.py files to arc-swift corresponding files to find oracles.

**Comment by amulyahwr** [comment]
Closing this issue since the required files (parserstate.py and transition.py) were uploaded.
