### ISSUE TITLE
Cannot prepare data for train

### ISSUE THREAD

**Issue by jheinecke** [alirezamshi/G2GTr#2]
Hi,
thanks for your interesting paper which refers to this repo. I wanted to replicate your results (on UD data) but got stuck very early on . I assume one has to install arc-swift to run `create_mappings.sh` and `gen_oracle_seq.py`. I tried this (on the data in `sample_data`:
```
cd /home/github/G2GTr/senttr
/home/github/arc_swift/utils/create_mappings.sh ../sample_data/train.conll > mappings-ptb.txt
python3 /home/github/arc-swift/src/gen_oracle_seq.py ../sample_data/train.conll --transsys ASd --mappings  mappings-ptb.txt  oracle.seq
```

But this fails already 

``` 
File "/users/jeuh6401/tools/arc-swift/src/utils.py", line 437, in processlines
    arcs[parent][i+1] = transsys.mappings['rel'][relation]
KeyError: 'nn'
```

So I guess the error must be elsewhere (I had to modify `gen_oracle_seq.py` to work with python3 since on Ubuntu 20 pip (for python2) is no longer available to install the missing packages.

`senttr.bash` do not work out of the box since the variables are empty.
Any ideas ?

thanks

**Comment by boldyrev** [comment]
Have exactly the same problem

**Comment by alirezamshi** [comment]
@jheinecke Thanks for your question. You should first follow the procedure in https://github.com/alirezamshi/G2GTr/tree/master/senttr#ud-treebanks to convert CoNLL-U format to CoNLL-X format. then do the same pre-processing as mentioned in https://github.com/alirezamshi/G2GTr/tree/master/senttr#wsj-penn-treebank . 

Please inform me if you'll have questions.

Best,

**Comment by boldyrev** [comment]
@alirezamshi Thanks for your answer.
I followed your recommendations, download UD Treebanks files, convert conllu to conllx, run this command
`python gen_oracle_seq.py ../data/en_ewt-ud-train.conllx train.seq --transsys ASd --mappings ../data/mappings-ptb.txt`
Output
`Traceback (most recent call last):
  File "/home/alex/code/arc-swift/src/gen_oracle_seq.py", line 25, in <module>
    write_gold_trans(state, fout)
  File "/home/alex/code/arc-swift/src/utils.py", line 469, in write_gold_trans
    fout.write("%s\n" % transsys.trans_to_str(t, state, pos, fpos))
  File "/home/alex/code/arc-swift/src/transition.py", line 530, in trans_to_str
    return "Shift\t%s\t%s" % (pos[state.buf[0]], fpos[state.buf[0]])
IndexError: list index out of range
`
Then I tried to do this:
`To include SWAP operation, you should update transition.py and parserstate.py files of arc-swift repository with our transition.py and parserstate.py files.`

In your repository file named as "tranistion.py", i renamed it to  "transition.py" and replace parserstate.py and transition.py in arc-swift repository, then again run:
`python gen_oracle_seq.py ../data/en_ewt-ud-train.conllx train.seq --transsys ASd --mappings ../data/mappings-ptb.txt`
got:
`Traceback (most recent call last):
  File "/home/alex/code/arc-swift/src/gen_oracle_seq.py", line 3, in <module>
    from transition import ArcSwift, ArcEagerReduce, ArcEagerShift, ArcStandard, ArcHybrid
  File "/home/alex/code/arc-swift/src/transition.py", line 1, in <module>
    class ArcStandard(TransitionSystem):
NameError: name 'TransitionSystem' is not defined
`

Any ideas?
Thanks

**Comment by alirezamshi** [comment]
@boldyrev thanks for your comment. 

you shouldn't completely replace the `transition.py` file, just update the `ArcStandard` class. I've again checked it, and it works. Let me know if you still have a problem.

Best,

**Comment by alirezamshi** [comment]
Good, I closed the issue, but don't hesitate to reopen it, if you have any problems.

Good luck!
