### ISSUE TITLE
Error on predict

### ISSUE THREAD

**Issue by boldyrev** [alirezamshi/G2GTr#3]
Hi,
trying to evaluate the model, fill predict.bash with my data, run it, get this out:

    Input is CONLL-X format
    Predicting the input file
    Set the max num of threads to 4
    Set the seed for generating random numbers to 1
    Set the device with ID -1 visible
    Override the default configs with parsed arguments
    Run the subcommand in mode predict
    Load the model
    Load the dataset
    Traceback (most recent call last):
      File "run.py", line 54, in <module>
        cmd(config)
      File "/home/alex/code/g2gt/senttr/parser/cmds/predict.py", line 50, in __call__
        dataset = TextDataset(vocab.numericalize(corpus))
      File "/home/alex/code/g2gt/senttr/parser/utils/vocab.py", line 269, in numericalize
        return self.map_arcs_bert(corpus)
      File "/home/alex/code/g2gt/senttr/parser/utils/vocab.py", line 221, in map_arcs_bert
        print("Percentage of unknown tokens:{}".format(self.unk_count * 1.0 / self.total_count * 100))
    ZeroDivisionError: float division by zero
    Finished Prediction
    Output is CONLL-X format
    Could not open system output file ../sample_data/predict_output/pred.conllx
    done

In debug mode (senttr/parser/utils/corpus.py)

![photo_2021-07-16_08-18-48](https://user-images.githubusercontent.com/740755/125896965-c384b359-bbdd-439b-bbf9-88f3faaf6893.jpg)

How can you see, len(line) always > 1 and sentences is empty

How can I solve it?

Thanks

**Comment by alirezamshi** [comment]
Hi, the line that you mentioned is referring to the empty line between sentences. Please check your input data. You can send it here.

Best,

**Comment by boldyrev** [comment]
Hi, my test file
[test.zip](https://github.com/alirezamshi/G2GTr/files/6838664/test.zip)

**Comment by alirezamshi** [comment]
Hi, the last line should be an empty line (line 7).

Best,

**Comment by boldyrev** [comment]
Line 7 is empty
![2021-07-19_10-24](https://user-images.githubusercontent.com/740755/126119712-808a5bd8-8b39-44fa-99f2-014388ee411c.png)

**Comment by boldyrev** [comment]
If insert 2 blank lines predict is run
